### ISSUE TITLE
keyup/down seems to have broken something

### ISSUE THREAD

**Issue by matthewscharles** [matthewscharles/keyboard-mapper#8]
Uncaught TypeError: Cannot set properties of undefined (setting 'Key')
    at e.<anonymous> (main.js:1:969)
    at Array.forEach (<anonymous>)
    at e.keymap_init (main.js:1:922)
    at new e (main.js:1:135)
    at main.js:1:2425
    at main.js:1:2442

**Comment by matthewscharles** [comment]
fixed for now, seemed to have dropped the keymap definition {}
